[package]
name = "ni"
version = "0.1.0"
edition = "2024"
# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
opt-level = "s"
lto = true
strip = true

[dependencies]
bevy = { version = "0.18", features = ["jpeg", "wav", "bevy_gltf", "bevy_solari"] }
bevy_egui = "0.39.1"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"
bevy-inspector-egui = "0.36"
bevy_hanabi = "0.18"
rand = "0.8"
